// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAA-eq6Z0s2lJ8qK7y2ruzu4cBIlsxynY',
    appId: '1:564330720671:web:08d83e8ef5c8812d8ea1aa',
    messagingSenderId: '564330720671',
    projectId: 'cinema-x-fcbbd',
    authDomain: 'cinema-x-fcbbd.firebaseapp.com',
    storageBucket: 'cinema-x-fcbbd.appspot.com',
    measurementId: 'G-Y25H5JM4MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-wmbmojweWnk8xoFw23XUsFWQh2hoC8',
    appId: '1:564330720671:android:7ae19d139bf2e5328ea1aa',
    messagingSenderId: '564330720671',
    projectId: 'cinema-x-fcbbd',
    storageBucket: 'cinema-x-fcbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBZrtdp1kppYumMQmOp_OkdYSrbjd3x4o',
    appId: '1:564330720671:ios:9d82ceb292781ef48ea1aa',
    messagingSenderId: '564330720671',
    projectId: 'cinema-x-fcbbd',
    storageBucket: 'cinema-x-fcbbd.appspot.com',
    iosClientId: '564330720671-neaf99oap020ct5pumv4lvorspt1fvca.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBZrtdp1kppYumMQmOp_OkdYSrbjd3x4o',
    appId: '1:564330720671:ios:9d82ceb292781ef48ea1aa',
    messagingSenderId: '564330720671',
    projectId: 'cinema-x-fcbbd',
    storageBucket: 'cinema-x-fcbbd.appspot.com',
    iosClientId: '564330720671-neaf99oap020ct5pumv4lvorspt1fvca.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAA-eq6Z0s2lJ8qK7y2ruzu4cBIlsxynY',
    appId: '1:564330720671:web:5fa9559df045b3e58ea1aa',
    messagingSenderId: '564330720671',
    projectId: 'cinema-x-fcbbd',
    authDomain: 'cinema-x-fcbbd.firebaseapp.com',
    storageBucket: 'cinema-x-fcbbd.appspot.com',
    measurementId: 'G-78YY8FZV7P',
  );
}
